version: "3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
