name: NodeJS front-end deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build
      run: |
        cd front-end
        npm install
        npm run build

    - name: Transfer
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.KGT_HOST }}
        username: ${{ secrets.KGT_USERNAME }}
        key: ${{ secrets.KGT_KEY }}
        source: "front-end/dist/*"
        target: "KGT/front-end/dist"
      
        
