name: NodeJS back-end deployment

on:
  push:
    branches: [main]

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: appleboy/scp-action@master
        if: ${{ always() }}
        with:
          host: ${{ secrets.KGT_HOST }}
          username: ${{ secrets.KGT_USERNAME }}
          key: ${{ secrets.KGT_KEY }}
          source: "back-end/*"
          target: "KGT/back-end/"

  deploy:
    runs-on: ubuntu-latest
    needs: transfer

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$KGT_KEY" > ~/.ssh/kgt.key
          chmod 600 ~/.ssh/kgt.key
          cat >>~/.ssh/config <<END
          Host kgt
            HostName $KGT_HOST
            User $KGT_USERNAME
            IdentityFile ~/.ssh/kgt.key
            StrictHostKeyChecking no
          END
        env:
          KGT_USER: ${{ secrets.KGT_USERNAME }}
          KGT_KEY: ${{ secrets.KGT_KEY }}
          KGT_HOST: ${{ secrets.KGT_HOST }}

      - name: Stop the server
        run: |
          ssh kgt
          npm install pm2@latest -g
          sudo pm2 stop all'

      - name: Build
        if: ${{ always() }}
        run: |
          ssh kgt 
          cd ~/KGT/back-end
          npm install'

      - name: Start the server
        if: ${{ always() }}
        run: |
          ssh kgt
          cd ~/KGT/back-end
          pm2 start server.js'
