name: NodeJS back-end deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build
      run: |
        cd back-end
        npm install
        
    - name: Transfer
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.KGT_HOST }}
        username: ${{ secrets.KGT_USERNAME }}
        key: ${{ secrets.KGT_KEY }}
        source: "back-end/*"
        target: "KGT/back-end/"
      
  start:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: RunServer
      run: |
        npm install pm2
        npm run start
        
