name: KGT deployment

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      server_updated: ${{ steps.check_files.outputs.server_updated }}
      client_updated: ${{ steps.check_files.outputs.client_updated }}

    steps:
      - name: checkout files
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check which files were updated
        id: check_files
        run: |
          echo "============= list all changed files ============="
          git diff --name-only HEAD^ HEAD > files.txt
          cat files.txt

          echo "========== check for changes to backend =========="
          while IFS= read -r file
          do
            echo $file
            if [[ $file == "back-end/"* ]]; then
              echo "::set-output name=server_updated::true"
              break
            else
              echo "File is not in back-end"
            fi
          done < files.txt

          echo "========== check for changes to frontend =========="
          while IFS= read -r file
          do
            echo $file
            if [[ $file == "front-end/"* ]]; then
              echo "::set-output name=client_updated::true"
              break
            else
              echo "File is not in front-end"
            fi
          done < files.txt

  build_backend:
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.server_updated == 'true'

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$KGT_KEY" > ~/.ssh/deploy.key
          sudo chmod 600 ~/.ssh/deploy.key
        shell: bash
        env:
          KGT_KEY: ${{ secrets.KGT_KEY }}

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: npm run deploy

  build_frontend:
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.client_updated == 'true'
    defaults:
      run:
        working-directory: front-end

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install npm dependencies
        run: npm install

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KGT_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "front-end/*"
          REMOTE_HOST: ${{ secrets.KGT_HOST }}
          REMOTE_USER: ${{ secrets.KGT_USER }}
          TARGET: "/home/ktkat/KGT/front-end/dist"
