name: NodeJS back-end deployment

defaults:
  run:
    working-directory: back-end

on:
  push:
    paths:
      - "back-end"
    branches: [main]

jobs:
  # check_commits:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     server_updated: ${{ steps.check_server.outputs.server_updated }}

  #   steps:
  #     - name: push commits

  #     - name: check if server was updated
  #       id: check_server
  #       run: |
  #         # here you need to replace "(sub-directories are updated)" with the actual if statement
  #         if [[ (sub-directories are updated) ]]; then
  #           echo "::set-output name=server_updated::true"
  #         else
  #           echo "::set-output name=server_updated::false"
  #         fi

  build:
    runs-on: ubuntu-latest
    # needs: [check_commits]
    if: needs.check_commits.outputs.server_updated == 'true'

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KGT_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.KGT_HOST }}
          REMOTE_USER: ${{ secrets.KGT_USER }}
          TARGET: "/home/ktkat/KGT/back-end/"

      # need some way of ssh'ing into machine before doing this. not sure if it's necessary anyway

      # - name: Run server
      #   run: |
      #     cd back-end
      #     npm run start

  #   steps:
  #     - name: Configure SSH
  #       run: |
  #         mkdir -p ~/.ssh/
  #         echo "$KGT_KEY" > ~/.ssh/kgt.key
  #         chmod 600 ~/.ssh/kgt.key
  #         cat >>~/.ssh/config <<END
  #         Host kgt
  #           HostName $KGT_HOST
  #           User $KGT_USER
  #           IdentityFile ~/.ssh/kgt.key
  #           StrictHostKeyChecking no
  #         END
  #       env:
  #         KGT_USER: ${{ secrets.KGT_USER }}
  #         KGT_KEY: ${{ secrets.KGT_KEY }}
  #         KGT_HOST: ${{ secrets.KGT_HOST }}

  #     - name: Stop the server
  #       run: ssh kgt 'pm2 stop all'

  #     - name: Build
  #         if: ${{ always() }}
  #       run: |
  #         ssh kgt
  #         'cd /home/ktkat/KGT/back-end && npm install'

  #     - name: Start the server
  #       if: ${{ always() }}
  #       run: |
  #         ssh kgt
  #         'pm2 start /home/ktkat/KGT/back-end/server.js'
