name: NodeJS front-end deployment

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: front-end

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install npm dependencies
        run: npm install

      - name: Build
        run: |
          cd front-end
          npm install
          npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KGT_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "front-end/dist/*"
          REMOTE_HOST: ${{ secrets.KGT_HOST }}
          REMOTE_USER: ${{ secrets.KGT_USER }}
          TARGET: "/home/ktkat/KGT/front-end/dist"
