name: upload & restart PM2 server

on:
  push:
    branches: [main]

jobs:
  restart_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./.ssh/deploy.key
          sudo chmod 600 ./.ssh/deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          KGT_KEY: ${{ secrets.KGT_KEY }}

      - name: Create env file
        run: |
          touch .env
          echo KGT_USER=${{ secrets.KGT_USER }} >> .env
          echo KGT_HOST=${{ secrets.KGT_HOST }} >> .env
          cat .env

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: npm run deploy
